### PR TITLE
Added Mouser part numbers to BOM

### PR DESCRIPTION
**Pull request by HSBallina**

### CODE REVIEW

**Comment by dojoe** [comment]
Hi Håkan!

Thank you for the PR! Instead of editing the (generated) BOM directly, I would prefer the Mouser PNs directly in the KiCAD schematic file and then generate the BOM from that. I could take care of this in a while (pretty busy with the day job right now), or if you have the time to update the .sch I would be much obliged :) Let me know what you prefer.

**Comment by HSBallina** [comment]
No worries! I can add the part numbers in KiCAD and update the PR.

**Comment by HSBallina** [comment]
Hi Joachim!
Sorry for the slow response. I've added the Mouser PN's in KiCAD, but since your original schematic was done in a previous version of KiCAD and I'm at version 6.0.6 and there seems to be some breaking changes I'm not sure whether to submit my updates or not. Or at least I ended up with a different folder/file structure after updating in KiCAD 6. I'm usually using DipTrace so I'm not entirely fluent in KiCAD so I could've missed something.

I'll try to back up to the master version and try again...

**Comment by dojoe** [comment]
I finally mustered the time to integrate your part numbers - thanks again!

**Pull request closed without merging**
